kind: pipeline
name: default
type: kubernetes

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: docker-registry.ngrok.io/jackett-vpn
    registry: docker-registry.ngrok.io
    tags: latest
    auto_tag: true